### ISSUE TITLE
Brute force folding API niggles

### ISSUE THREAD

**Issue by maxhwardg** [Edgeworth/memerna#11]
I ran into some behaviour with the brute force folder that might be improvable.

- If you ask it to compute the partition function, it will not compute a collection of secondary structures.
- There is no option to ignore CTDs (that is, only compute a Secondary).
- The Run function API being monolithic and requiring many arguments might be better replaced by a data driven API with overloading.

**Comment by maxhwardg** [comment]
One note is that if you just want to compute all secondary structures (without CTDs) there is probably a faster specialised algorithm(?)

**Comment by Edgeworth** [comment]
Yerp, brute force suboptimal is deliberately implemented suboptimally.

I agree the brute force API needs improvement.

**Comment by Edgeworth** [comment]
Brute force API is being improved, see BruteCfg and BruteResult
