### ISSUE TITLE
Sum of probabilities is > 1 for some short sequences

### ISSUE THREAD

**Issue by maxhwardg** [Edgeworth/memerna#17]
Sum of probabilities for all structures of UAGCUAGCUUGAUC = 1.001911832338799.

This was computed by the following.

(1) Enumerating all possible secondary structures.
(2) Using efn to compute their energy. (Note that this should underestimate since it only takes the optimal CTD arrangement)
(3) Calling Boltzmann on the energies, then divide by Q to get a probability.
(4) Sum probabilities.

I don't have a (simple) code example yet since I compute all this via SWIG constructed python bindings inside a script.

**Comment by Edgeworth** [comment]
Can you check if this still happens after https://github.com/Edgeworth/memerna/commit/0e478fd26915393ed57d2f4413e62216910e413d ?

**Comment by maxhwardg** [comment]
Seems to be fixed now.
