### ISSUE TITLE
An RnaPackage can only be created from an ArgParse

### ISSUE THREAD

**Issue by maxhwardg** [Edgeworth/memerna#2]
The RnaPackage class in bridge.h can only be created from an RnaPackageFromArgParse. This seems cumbersome when using the API from code.

**Comment by Edgeworth** [comment]
If you're creating from code, wouldn't you know which one you want? In that case, can't you just construct the appropriate derived class?

**Comment by Edgeworth** [comment]
Closed since you can construct the derived class.
