### ISSUE TITLE
SuboptCfg is not respected

### ISSUE THREAD

**Issue by maxhwardg** [Edgeworth/memerna#24]
Consider the following

```
auto all_sub = ctx.SuboptimalIntoVector(mrna::Primary(p), {-1, -1, false});
```

This produces unexpected results with the following input: "UACGUAGC"

Subopt 0 = Segmentation fault
Subopt 1 = Empty output
Brute = Segmentation fault

**Comment by Edgeworth** [comment]
-1 is not a supported number for suboptcfg. Can you retry with the defaults? I.e. max_structures and max_e

**Comment by maxhwardg** [comment]
In that case remove the following comments:
// maximum energy delta from minimum. -1 means no limit
// maximum number of structures to report.  -1 means no limit

**Comment by maxhwardg** [comment]
The defaults work as intended.
