### ISSUE TITLE
Subopt hairpin loop regression

### ISSUE THREAD

**Issue by maxhwardg** [Edgeworth/memerna#25]
They seem to output hairpin loops with <3 unpaired nts. This was probably introduced by 47357f6e7bf44181a3d79940f9a26a93e30df9f4 (see my comment there)

A small breaking case is "UACGACU"

The brute force subopt is not affected.

**Comment by maxhwardg** [comment]
An extra bit of information that may be useful.

In all tested cases, if I add up the boltzmann energies of all subopt, the brute force subopt seems to produce the same answer as the default partition function alg.

**Comment by Edgeworth** [comment]
Lonely pairs are disallowed by default so I don't think this is the cause of the issue. Could you try with the latest patch and see if it fixes it?
