### ISSUE TITLE
`rnapy.run build --regenerate` sometimes raises exception

### ISSUE THREAD

**Issue by turix2** [Edgeworth/memerna#29]
(Sorry, I know this is a very minor / low priority issue, but the fix seems very easy too, so I went ahead and filed it.)

When using the `--regenerate` option with `rnapy.run build`,  the call to `shutil.rmtree(path)` in `rnapy/build/build_cfg.py` will sometimes raise an exception because `path` does not exist (if you are experimenting with different command line options).

This usually makes sense because it is assumed you will use the `--regenerate` option if you want to wipe an _existing_ build folder at path.  But it's not obvious (nor documented) to the user _which_ of the command-line arguments contribute to the name of the build folder. 

Thus I suggest that`--regenerate` not fail when the build folder doesn't already exist.  This might be as easy as using the `ignore_errors` flag in the `rmtree()` call, like:  `shutil.rmtree(path, ignore_errors=True)`.

**Comment by Edgeworth** [comment]
Thanks for the report, seems very reasonable!
