### ISSUE TITLE
config.cpp does not load default algorithms

### ISSUE THREAD

**Issue by maxhwardg** [Edgeworth/memerna#4]
When using an ArgParse, config.cpp expects the dp_alg (and other) flags to be set instead of loading a default, as is done in other places.

**Comment by maxhwardg** [comment]
Actually this is not true. config.h populates defaults. The real issue was caused by bridge.h implicitly expecting MODEL_OPTS (and other args) to be set without binding them itself leading to a run time crash.

**Comment by Edgeworth** [comment]
Argument parsing needs to be cleaned up a bit. Currently, users are expected to bind the args themselves. It shouldn't always bind though. Some helpers would be good to add.

**Comment by Edgeworth** [comment]
Fixed
