### ISSUE TITLE
Secondary type

### ISSUE THREAD

**Issue by maxhwardg** [Edgeworth/memerna#7]
Secondary structures can be defined without a primary sequence in mind (such as a design problem). I think it would be useful to have a type capturing just a secondary structure. It seems like a vector<int> with a particular format is used for this. It might be good to give this an explicit type and interface. I used to call this a "Matching".

Also, using members like "r" and "p" is hard to interpret.

**Comment by Edgeworth** [comment]
This is on my TODO list.

**Comment by Edgeworth** [comment]
This is fixed. The type is called "Secondary"
